### ISSUE TITLE
As a staff, I will help customer to take their order by using this system.

### ISSUE THREAD

**Issue by JsenPua** [JsenPua/McDonald-Restaurant#1]
hi all, do u all see my message?

**Comment by PohSekLee** [comment]
yes

**Comment by JsenPua** [comment]
so how to do the coding :(

**Comment by PohSekLee** [comment]
waiting for other first 0.0
i also dont know how to do it. haha

**Comment by JsenPua** [comment]
i can't see swati at here....

**Comment by PhangCW** [comment]
Hi , everyone

**Comment by PhangCW** [comment]
`public void addRecord(OrderList o) {
        String s = "INSERT INTO " + tableName + " VALUES(?, ?, ?, ?)";
        String orderID = o.getOrderID();
        String transID = o.getTransID();
        String itemCode = o.getItem().getItemCode();
        int quantity = o.getQuantity();

        try {
            stmt = conn.prepareStatement(s);
            stmt.setString(1, orderID);
            stmt.setString(2, transID);
            stmt.setString(3, itemCode);
            stmt.setInt(4, quantity);
            stmt.executeUpdate();
            System.out.println(LocalDateTime.now() + " " + orderID + " is inserted Successful in database.\n");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error in orderDA addRecord():  " + ex.getMessage(), "ERROR in database", JOptionPane.ERROR_MESSAGE);
        }
    }`

**Comment by JsenPua** [comment]
private class AddListener implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            String itemCode = jtfItemCode.getText().toUpperCase();
            String itemName = jtfItemName.getText();
            double price = Double.parseDouble(jtfPrice.getText());
            Category category = (new CategoryDA()).getRecord(categoryID);
            String description = jtaDescription.getText();
            String selectedFile = "";
            String status = statusList[jcboStatus.getSelectedIndex()];
            boolean canContinue = false;
            try {
                selectedFile = jfcPhoto.getSelectedFile().getAbsolutePath();
                canContinue = true;
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(null, "Error Insert: Image is null.", "Insert Error", JOptionPane.ERROR_MESSAGE);
            }
            if (canContinue) {
                try {
                    ImageIcon imageIcon = new ImageIcon(selectedFile);
                    URL url = new URL("file:///" + selectedFile);
                    imgPhoto = new ItemImg(imageIcon, url);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Error insert" + ex.getMessage());
                }
                Item item = itemControl.selectRecord(itemCode);
                if (item != null) {
                    JOptionPane.showMessageDialog(null, "Item Existed", "SAME RECORD IS FOUND", JOptionPane.ERROR_MESSAGE);
                } else {
                    try {
                        item = new Item(itemCode, itemName, price, category, description, imgPhoto, status);
                        itemControl.addRecord(item);
                    } catch (IOException ex) {
                        Logger.getLogger(MaintainAddItemFrame.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (Exception exc) {
                        JOptionPane.showMessageDialog(null, "Insert Error: " + exc.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    item = itemControl.selectRecord(itemCode);
                    if (item != null) {
                        JOptionPane.showMessageDialog(null, itemCode + " is inserted Successful.\n", "Insert Successful", JOptionPane.INFORMATION_MESSAGE);
                        clear();
                        String itemcode = itemCode;
                        int itemNum;
                        itemNum = Integer.parseInt(itemcode.substring(1));
                        itemNum += 1;
                        itemcode = "I" + itemNum;
                        jtfItemCode.setText(itemcode);
                    }
                }

            }
        }
    }

**Comment by JsenPua** [comment]
is this code fine for the order part?

**Comment by PhangCW** [comment]
Wow, such a long code
Hopefully there's not error

**Comment by PohSekLee** [comment]
Can you give some description for your code?

**Comment by JsenPua** [comment]
@PhangCW  ermm, it should be, because i seek from other's help when i faced problem. If got any problem found, can give a comment also ^^

**Comment by SwatiKiran0211** [comment]
@JsenPua , code seems fine..

**Comment by JsenPua** [comment]
@PohSekLee  actually it is about adding a new item into the order.

**Comment by JsenPua** [comment]
@SwatiMilaine  ya, thanks though

**Comment by PohSekLee** [comment]
@JsenPua Okay, i think it's fine for that.

**Comment by JsenPua** [comment]
i think we should close this issue since all are agreed with it.
