### ISSUE TITLE
As a customer, I would like to pay cash or credit/debit card.

### ISSUE THREAD

**Issue by JsenPua** [JsenPua/McDonald-Restaurant#10]
I will manage the coding part for payment. Any suggestion?

**Comment by JsenPua** [comment]
Hello everyone, this is one of my sample code -->
public class ProceedListener implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            double amountPaid = 0;
            boolean exception = true;
            if (jrbIsNotMember.isSelected()) {
                memberDB = "M9000";
            } else {
                memberDB = jtfMemberID.getText();
            }
            if (jcbVoucher10.isSelected()) {
                totalDiscount = totalDiscount + 10;
            }
            jlbTotalDiscountI.setText(String.format("%.2f", totalDiscount) + "");
            grandTotal = subTotal - totalDiscount - gst;
            jlbGrandTotalI.setText(String.format("%.2f", grandTotal) + "");
            balanceDue = grandTotal;
            jlbBalanceDueI.setText(String.format("%.2f", balanceDue) + "");
            double balanceDue2 = 0;
            do {
                try {
                    do {
                        if (JOptionPane.showConfirmDialog(null, "Proceed to payment?", "Payment", JOptionPane.WARNING_MESSAGE) == 0) {
                            amountPaid = Double.parseDouble(JOptionPane.showInputDialog(null, "Amount Paid :", "Payment", JOptionPane.INFORMATION_MESSAGE));
                            balanceDue2 = balanceDue - amountPaid;
                            if (balanceDue2 <= 0) {
                                jlbBalanceDueI.setText("0.00");
                                change = amountPaid - balanceDue;
                                jlbChangeI.setText(String.format("%.2f", change) + "");
                                balanceDue = 0;
                            } else {
                                balanceDue = balanceDue2;
                                JOptionPane.showMessageDialog(null, "Insufficient Amount", "Payment", JOptionPane.ERROR_MESSAGE);
                            }
                            exception = false;
                        }

                    } while (balanceDue2 > 0);

                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Enter Only Integer!");
                    exception = true;
                }
            } while (exception == true);
            newTrans();
            MaintaiItemFrame newItemFrame = new MaintaiItemFrame(stf);
            ((Window) getRootPane().getParent()).dispose();
        }

    }

**Comment by JsenPua** [comment]
I manage to do it in cash form, is it ok?

**Comment by PohSekLee** [comment]
Can you explain some of your code?

**Comment by JsenPua** [comment]
some? which part u not understand? You can specified it, perhaps i could explain to you?

**Comment by SwatiKiran0211** [comment]
Ok..... look fine, you can proceed...

**Comment by PohSekLee** [comment]
if (JOptionPane.showConfirmDialog(null, "Proceed to payment?", "Payment", JOptionPane.WARNING_MESSAGE) == 0) {
                        amountPaid = Double.parseDouble(JOptionPane.showInputDialog(null, "Amount Paid :", "Payment", JOptionPane.INFORMATION_MESSAGE));
                        balanceDue2 = balanceDue - amountPaid;
                        if (balanceDue2 <= 0) {
                            jlbBalanceDueI.setText("0.00");
                            change = amountPaid - balanceDue;
                            jlbChangeI.setText(String.format("%.2f", change) + "");
                            balanceDue = 0;
                        } else {
                            balanceDue = balanceDue2;
                            JOptionPane.showMessageDialog(null, "Insufficient Amount", "Payment", JOptionPane.ERROR_MESSAGE);
                        }

**Comment by PhangCW** [comment]
I guess your code  is fine , if possible write some comments to explain what are the code can perform
More easy to read

**Comment by JsenPua** [comment]
if you can see there, it actually  calculating the balance needed to pay back to customer and an error message will be displayed if insufficient amount.
