### ISSUE TITLE
As a customer, I would like to use my points to redeem items

### ISSUE THREAD

**Issue by SwatiKiran0211** [JsenPua/McDonald-Restaurant#11]

**Comment by SwatiKiran0211** [comment]
`private void jbtRedeemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRedeemActionPerformed
        String ID = generateRandomString();
        int choice1;

        Redeem redeem = maintainRedControl.selectRecord(ID);
        Toys toys = maintainRedItem.selectRecord2(jtfName.getText());
        Member member = memControl.selectRecord(jtfID.getText());
        try {
            if (jtfID.getText().isEmpty() || jtfName.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "The Member ID or Item Name is not provided");
            } else if (member == null || toys == null ) {
                JOptionPane.showMessageDialog(null, "The member ID or the name of item provided is not valid or available");

            } else {
                int point = Integer.parseInt(jtfPoints.getText());
                int stock = Integer.parseInt(jtfStock.getText());
                if (member.getLoyaltyPoint() > point && toys.getStockCount() > 0) {
                    redeem = new Redeem(ID, member, toys);
                    maintainRedControl.addRedeem(redeem);
                    point = member.getLoyaltyPoint() - point;
                    stock = toys.getStockCount() - 1;
                    member = new Member(member.getMbrID(), member.getMemberName(), member.getIcNo(), member.getContactNo(), member.getHomeAddress(), point, member.getMemStartDate(), member.getMemEndDate(), member.getMbrType());
                    memControl.updateMember(member);
                    toys = new Toys(toys.getRdiCode(), toys.getRdiName(), toys.getPoints(), stock);
                    maintainRedItem.updateRedeemItem(toys);
                    JOptionPane.showMessageDialog(null, "Redeemed successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
                    jtfMemPoint.setText("" + member.getLoyaltyPoint());
                    jtfStock.setText("" + stock);
                    clearFields();
                } else {
                    JOptionPane.showMessageDialog(null, "Insufficient points or insufficient stock", "Information", JOptionPane.INFORMATION_MESSAGE);
                }

            }

        } catch (NumberFormatException ex) {
            ex.printStackTrace();
        }`

**Comment by SwatiKiran0211** [comment]
What do you guys think about this function when user chooses an item to redeem~?

**Comment by PohSekLee** [comment]
Can you average your code ? 0.0

**Comment by PohSekLee** [comment]
Ya, I think it should be okay.

**Comment by PhangCW** [comment]
I suggest under the catch method, display a meaningful message to the user.

**Comment by JsenPua** [comment]
The JOption Pane for "Insufficient point or insufficient stock", do user really can differentiate when they encounter either one of the problem>?

**Comment by SwatiKiran0211** [comment]
@PohSekLee @PhangCW , well, the stock and the point is already in the User Interface, so the user can know exactly what is the error~
