### ISSUE TITLE
Staff can login to system using ID and password

### ISSUE THREAD

**Issue by PhangCW** [JsenPua/McDonald-Restaurant#12]

**Comment by PhangCW** [comment]
This is the code where the user clicks on the sign in button
` private class SignInListener implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            String id = jtfId.getText();
            Staff stf = stfControl.selectRecord(id);

            if (stf != null && jpfPassword.getText().equals(stf.getPassword())) {
                JOptionPane.showMessageDialog(null, "WELCOME TO McDonald's!!");
                dispose();

                Staff staff = new Staff(jtfId.getText());
                
                 Main frame = new Main(staff);
                
                 
                count =0;
               

            } else {
                JOptionPane.showMessageDialog(null, "Invalid user ID or password", "STAFF NOT FOUND", JOptionPane.ERROR_MESSAGE);
                jpfPassword.setText("");
                warning();
            }
        }
    }

    public void warning() {
        
        count++;
        if (count == 3) {
            JOptionPane.showMessageDialog(null, "You're not an authorised user", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }`

**Comment by PohSekLee** [comment]
Is it the user log in with wrong password or id 3 times
then will directly exit the system?

**Comment by PhangCW** [comment]
@PohSekLee  Yes

**Comment by SwatiKiran0211** [comment]
Is there any hashing for the password in the database?

**Comment by PhangCW** [comment]
@SwatiMilaine Erm, according to the user story . It didnt mention this kind of features

**Comment by SwatiKiran0211** [comment]
Well, but it is necessary.. Imagine someone steals customer's Credit card details.

**Comment by PohSekLee** [comment]
Wahhh
So nice

**Comment by PhangCW** [comment]
@SwatiMilaine  ermm, our database wont store any customer's credit card details

**Comment by JsenPua** [comment]
JOptionPane.showMessageDialog(null, "Invalid user ID or password", "STAFF NOT FOUND", JOptionPane.ERROR_MESSAGE);
Do user really know which error they made if they only fall into one of the problem?

**Comment by PhangCW** [comment]
@JsenPua This is to prevent unauthorized user to login to another person's account 
So it's necessary to display message like this
