### ISSUE TITLE
As a staff, I would like to manage redeemable items

### ISSUE THREAD

**Issue by SwatiKiran0211** [JsenPua/McDonald-Restaurant#14]

**Comment by PohSekLee** [comment]
This code is for adding new redeem item.
Is it okay for that?

        String ID = generateRandomString();
        int point = 0;
        int choice1;

        Toys redeemItem = reditemControl.selectRecord(ID);
        
        if (jtfRdiName.getText().equals("") || jtfPointsNeed.getText().isEmpty()) 
            JOptionPane.showMessageDialog(null, "Please make sure to fill in all the necessary fields");

        else {
                if (!(jtfRdiName.getText().length() < 31 && jtfPointsNeed.getText().length() < 4)) {

                    JOptionPane.showMessageDialog(null, "Please make sure to fill in all the necessary fields");
                } else {

                    choice1 = JOptionPane.showConfirmDialog(null, "Do you confirm registration? Click on 'Yes' to confirm and 'No' to go back",
                            "Confirmation", JOptionPane.YES_NO_OPTION);

                    if (choice1 == JOptionPane.YES_OPTION) {
                        redeemItem = new Toys(ID, jtfRdiName.getText(), Integer.parseInt(jtfPointsNeed.getText()),Integer.parseInt(jtfStock.getText()));

                        reditemControl.addRedeemItem(redeemItem);
                        JOptionPane.showMessageDialog(null, jtfRdiName.getText() + " successfully added");
                        JOptionPane.showMessageDialog(null, "Here is the ID for "
                                + jtfRdiName.getText() + ": " + ID);

                        clearFields();
                    }
                }
            }

**Comment by JsenPua** [comment]
wow, impressive....how long does it take you to complete this.

**Comment by PohSekLee** [comment]
Haha
around 3 to 4 hours =)

**Comment by JsenPua** [comment]
wow, so fast. It make me amazed :+1:

**Comment by PohSekLee** [comment]
You also not bad (y)

**Comment by PohSekLee** [comment]
You also not bad 
:+1:

**Comment by PhangCW** [comment]
Hey ladies and gentlemen 
Dont flirt here , btw 
You all did well,

**Comment by SwatiKiran0211** [comment]
Ok, nothing else to change.. looks good

**Comment by PohSekLee** [comment]
@SwatiMilaine Thank you <3
