### ISSUE TITLE
As a staff, I need to be able to manage customer memberships

### ISSUE THREAD

**Issue by SwatiKiran0211** [JsenPua/McDonald-Restaurant#2]
**For membership renewal**

`final java.util.Calendar cal = GregorianCalendar.getInstance();
  cal.setTime(date);
  cal.add(GregorianCalendar.MONTH, 2);`

**For adding a new member**

`if (jtfName.getText().equals("") || jtfIC.getText().equals("")
                || jtfContact.getText().equals("") || jtaAddress.getText().equals("")
                || jckBasic.isSelected() == false && jckPremium.isSelected() == false) 
            JOptionPane.showMessageDialog(null, "Please make sure to fill in all the necessary fields");

        else {
                if (!(jtfName.getText().length() < 31 && jtfIC.getText().length() < 15
                        && jtfContact.getText().length() < 13 && jtaAddress.getText().length() < 101)) {

                    JOptionPane.showMessageDialog(null, "Please make sure to fill in all the necessary fields");
                } else {

                    choice1 = JOptionPane.showConfirmDialog(null, "Do you confirm registration? Click on 'Yes' to confirm and 'No' to go back",
                            "Confirmation", JOptionPane.YES_NO_OPTION);

                    if (jckBasic.isSelected()) {
                        type = jckBasic.getText();
                        cal.add(GregorianCalendar.MONTH, 6);
                    } else {
                        type = jckPremium.getText();
                        cal.add(GregorianCalendar.YEAR, 1);
                    }

                    if (choice1 == JOptionPane.YES_OPTION) {
                        member = new Member(ID, jtfName.getText(), jtfIC.getText(), jtfContact.getText(), jtaAddress.getText(),
                                point, date, cal.getTime(), type);

                        memControl.addMember(member);
                        JOptionPane.showMessageDialog(null, jtfName.getText() + " successfully added");
                        JOptionPane.showMessageDialog(null, "\tSUCCESSFULLY REGISTERED AS MEMBER OF MCDONALD'S\n\nHere is "
                                + jtfName.getText() + "'s Member ID: " + ID);`

**Comment by SwatiKiran0211** [comment]
Is 2 months of renewal enough?

**Comment by JsenPua** [comment]
i think 2 month quite fast, how about 12 months(1 year)?

**Comment by SwatiKiran0211** [comment]
ok, that makes sense. Anyone else have any other suggestion?

**Comment by PohSekLee** [comment]
I agree with Jensen,1 year is better.

**Comment by PhangCW** [comment]
Actually what is the thing for ?
Just some calendar variables?

**Comment by SwatiKiran0211** [comment]
@PhangCW , this is for  renewing the membership..
So..when the staff clicks on renew button, the system will add two months to the expiration date.

**Comment by PhangCW** [comment]
Oh , i see 
but according to the new changes , should be 12 months

**Comment by JsenPua** [comment]
the date is to for manage the membership expired date right? 
but how u confirm about the renewal? 
because from the code, i can only see the time management , how about to renew?

**Comment by SwatiKiran0211** [comment]
**Updated Membership renewal**

`if (member.getMemEndDate().before(date)) {
            if (jtfType.getText().equals("Basic Membership")) {
                cal.add(GregorianCalendar.MONTH, 6);
            } else if (jtfType.getText().equals("Premium Membership")) {
                cal.add(GregorianCalendar.YEAR, 1);
            }`

**Update Member Details**

`if (member != null) {
            try {
                java.util.Date startDate = date.parse(jtfStartDate.getText());
                java.sql.Date sqlStartDate = new java.sql.Date(startDate.getTime());

                java.util.Date endDate = date.parse(jtfEndDate.getText());
                java.sql.Date sqlEndDate = new java.sql.Date(endDate.getTime());

                member = new Member(ID, jtfName.getText(), jtfIC.getText(), jtfContact.getText(), jtaAddress.getText(),
                        Integer.parseInt(jtfPoints.getText()), sqlStartDate, sqlEndDate, jtfType.getText());
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            memControl.updateMember(member);
            JOptionPane.showMessageDialog(null, jtfName.getText() + " updated");`

**Deactivate Membership**

`if (member != null) {
            try {
                java.util.Date startDate = date.parse(jtfStartDate.getText());
                java.sql.Date sqlStartDate = new java.sql.Date(startDate.getTime());

                java.util.Date endDate = date.parse(jtfEndDate.getText());
                java.sql.Date sqlEndDate = new java.sql.Date(endDate.getTime());

                member = new Member(ID, jtfName.getText(), jtfIC.getText(), jtfContact.getText(), jtaAddress.getText(),
                        Integer.parseInt(jtfPoints.getText()), sqlStartDate, sqlEndDate, jtfType.getText());

                int option = JOptionPane.showConfirmDialog(null, "Confirm delete member ?", "Delete", JOptionPane.YES_NO_OPTION);
                if (option == JOptionPane.YES_OPTION) {
                    memControl.removeMember(member);

                    JOptionPane.showMessageDialog(null, jtfName.getText() + " deleted");`

**Comment by SwatiKiran0211** [comment]
here are the changes I made. Hopefully it is agreeable @JsenPua @PhangCW @PohSekLee

**Comment by PohSekLee** [comment]
Yes, I agree.

**Comment by PhangCW** [comment]
ya , now is perfect

**Comment by JsenPua** [comment]
how about no?

**Comment by SwatiKiran0211** [comment]
Really @JsenPua ? You don't agree?? Then how long do you want each type of membership to have? For **Basic Membership** and **Premium Membership**?

**Comment by JsenPua** [comment]
Kind of.but seems like everyone is agreed, then i think it is fine :)
