### ISSUE TITLE
As a manager, I would like to manage my staff

### ISSUE THREAD

**Issue by PhangCW** [JsenPua/McDonald-Restaurant#3]
`JPanel panelNorth = new JPanel(new GridLayout(2,2,0,10));
  panelNorth.add(new JLabel("Search by: "));
  panelNorth.add(jcbSearch);
  panelNorth.add(new JLabel("Enter your Search: "));
  panelNorth.add(jtfSearch);`

**Comment by PhangCW** [comment]
So, the staff table will show all the staff at first.
You can filter or search for a certain person using the search by or search !

**Comment by SwatiKiran0211** [comment]
Yea, we need the filter function to find groups of staff we are searching for..

**Comment by JsenPua** [comment]
So, which field will it be show beside staff's name?

**Comment by PhangCW** [comment]
This is just a partial of the code , i will display the relevant information about the staff, ^^

**Comment by SwatiKiran0211** [comment]
ok, @PhangCW ,how about the staff module **main functions**?

**Comment by PhangCW** [comment]
@SwatiMilaine Actually this is just a partial of the code which just allow to search for staff

**Comment by PohSekLee** [comment]
Can i know this is search by using staff name or depend on staff id?

**Comment by PhangCW** [comment]
`public StaffTable(Staff staff) {
        jcbSearch = new JComboBox(new Object[]{"Staff ID", "Staff Name", "Staff Position"});
        tableModel = new StaffTableModel();
        resultTable = new JTable(tableModel);
        jcbSearch.setBackground(Color.orange);
        jtfSearch.setBackground(Color.orange);
        
        stf = staff.getId();
        JPanel panelNorth = new JPanel(new GridLayout(2,2,0,10));
        panelNorth.add(new JLabel("Search by: "));
        panelNorth.add(jcbSearch);
        panelNorth.add(new JLabel("Enter your Search: "));
        panelNorth.add(jtfSearch);
        
        
        JPanel panelSouth = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        resultTable.setBackground(Color.orange);
         jcp = new JScrollPane(resultTable);`

**Comment by SwatiKiran0211** [comment]
@PhangCW , this is good~ But what about adding a new staff?

**Comment by PhangCW** [comment]
@PohSekLee  actually it can allow you to choose what category you wanted to search , if you want to search by ID , then just can choose from the comboBox

**Comment by PohSekLee** [comment]
Ohhh, It is a good filter function for searching.

**Comment by PhangCW** [comment]
**Add New Staff**
` if (staff == null) {
                    double salary = Double.parseDouble(jtfSalary.getText());
                    decision = true;

                    try {

                        String selectedFile = jfcPhoto.getSelectedFile().getAbsolutePath();
                        ImageIcon imageIcon = new ImageIcon(selectedFile);

                        URL url1 = new URL("file:///" + selectedFile);
                        Icon icon = new Icon(imageIcon, url1);

                        staff = new domain.Staff(id, jtfName.getText(), jpfPassword.getText(), jtfContact.getText(), jtaAddress.getText(), jtfIc.getText(), position, salary, icon);

                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "exception occurs" + ex.getMessage());
                    }

                }
                int option = JOptionPane.showConfirmDialog(null, "Confirm adding as employee ?", "New Employee", JOptionPane.YES_NO_OPTION);
                if (option == JOptionPane.YES_OPTION) {
                    stfControl.addRecord(staff);
                    JOptionPane.showMessageDialog(null, "Your ID is " + id);

                    Clear();
                }`

**Update Staff Information**

` try {
                String selectedFile = jfcPhoto.getSelectedFile().getAbsolutePath();

                ImageIcon imageIcon = new ImageIcon(selectedFile);

                URL url = new URL("file:///" + selectedFile);

                icon = new Icon(imageIcon, url);

            } catch (NullPointerException ex) {
                ImageIcon imageIcon = staff.getIcon().getImage();
                icon = new Icon(imageIcon);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "exception occurs" + ex.getMessage());
            }

            int option = JOptionPane.showConfirmDialog(null, "Confirm update " + jtfName.getText() + "'s information?", "Update Employee", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                stf = new domain.Staff(id, jtfIc.getText(), jtfName.getText(), jpfPassword.getText(), jtfContact.getText(), jtaAddress.getText(), position, salary, icon);
                try {
                    stfControl.updateRecord(stf);
                } catch (SQLException | IOException ex) {
                    Logger.getLogger(MaintainStaff.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, jtfName.getText() + "'s information updated successfully");
                Clear();`

**Delete Staff Record**

`int option = JOptionPane.showConfirmDialog(null, "Do you wish to remove " + jtfName.getText() + "?", "Delete Employee", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                stfControl.deleteRecord(stf);
                JOptionPane.showMessageDialog(null, jtfName.getText() + " successfully delete");

                Clear();`

**Comment by PhangCW** [comment]
@SwatiMilaine  these are the main functions of staff maintenance

**Comment by SwatiKiran0211** [comment]
Ok, looks fine too ^^
