### ISSUE TITLE
As a staff, I will update the menu from time to time.

### ISSUE THREAD

**Issue by PohSekLee** [JsenPua/McDonald-Restaurant#8]

**Comment by PohSekLee** [comment]
JPanel jpCenter = new JPanel(new GridLayout(7, 2));
 jpCenter.add(new JLabel("Item Code"));
jpCenter.add(jtfItemCode);

**Comment by PohSekLee** [comment]
item.setItemName(itemName);
                    item.setPrice(price);
                    item.setCategory(category);
                    item.setDescription(description);
                    item.setItemImg(imgPhoto);
                    item.setStatus(status);
                    itemControl.updateRecord(item);
                    JOptionPane.showMessageDialog(null, itemCode + " is updated Successful.\n", "Insert Successful", JOptionPane.INFORMATION_MESSAGE);

**Comment by PohSekLee** [comment]
This code is for updating item in menu. 
If update successful it will pop up a successful message to user.

**Comment by PhangCW** [comment]
This is good and amazing

**Comment by SwatiKiran0211** [comment]
@PohSekLee , how about if it is not successful?

**Comment by JsenPua** [comment]
But, is that only prompt up successfully message only? how about the implementations?

**Comment by PohSekLee** [comment]
@SwatiMilaine 

Okay, That one i just did it. This is the code included for the error.

if (item != null) {
                try {
                    item.setItemName(itemName);
                    item.setPrice(price);
                    item.setCategory(category);
                    item.setDescription(description);
                    item.setItemImg(imgPhoto);
                    item.setStatus(status);
                    itemControl.updateRecord(item);
                    JOptionPane.showMessageDialog(null, itemCode + " is updated Successful.\n", "Insert Successful", JOptionPane.INFORMATION_MESSAGE);

                } catch (IOException ex) {
                    Logger.getLogger(MaintainAddItemFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No such item code.", "RECORD NOT FOUND", JOptionPane.ERROR_MESSAGE);
            }

**Comment by PohSekLee** [comment]
@JsenPua 

Hi, this is the implementation code for updating item in the menu.

private class UpdateListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            String itemCode = jtfItemCode.getText().toUpperCase();
            String itemName = jtfItemName.getText();
            double price = Double.parseDouble(jtfPrice.getText());
            Category category = (new CategoryDA()).getRecord(categoryID);
            String description = jtaDescription.getText();
            String selectedFile;
            String status = statusList[jcboStatus.getSelectedIndex()];
            Item item = itemControl.selectRecord(itemCode);
            try {
                selectedFile = jfcPhoto.getSelectedFile().getAbsolutePath();
                ImageIcon imageIcon = new ImageIcon(selectedFile);
                URL url = new URL("file:///" + selectedFile);
                imgPhoto = new ItemImg(imageIcon, url);
            } catch (NullPointerException ex) {
                ImageIcon imageIcon = item.getItemImg().getImage();
                imgPhoto = new ItemImg(imageIcon);
            } catch (Exception exc) {
                JOptionPane.showMessageDialog(null, "Error in image: " + exc.getMessage());
            }

            if (item != null) {
                try {
                    item.setItemName(itemName);
                    item.setPrice(price);
                    item.setCategory(category);
                    item.setDescription(description);
                    item.setItemImg(imgPhoto);
                    item.setStatus(status);
                    itemControl.updateRecord(item);
                    JOptionPane.showMessageDialog(null, itemCode + " is updated Successful.\n", "Insert Successful", JOptionPane.INFORMATION_MESSAGE);

                } catch (IOException ex) {
                    Logger.getLogger(MaintainAddItemFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No such item code.", "RECORD NOT FOUND", JOptionPane.ERROR_MESSAGE);
            }

        }
    }

**Comment by SwatiKiran0211** [comment]
@PohSekLee , ok, thanks.

**Comment by JsenPua** [comment]
hmmm, looks great. I bet you have put a lot of effort on it
